server:
  compression:
    enabled: false
  port: 8091
  servlet:
    context-path: /api/v1
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


---
spring:
  profiles: test
---
spring:
  profiles: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration